{% set name = "eodatasets3" %}
{% set version = "0.30.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 17944c3b63f6ea835c2ac5915914b7faf1e9a3739adc07166ed00e7b562ecdd2

build:
  entry_points:
    - eo3-validate = eodatasets3.validate:run
    - eo3-prepare = eodatasets3.scripts.prepare:run
    - eo3-recompress-tar = eodatasets3.scripts.recompress:main
    - eo3-package-wagl = eodatasets3.scripts.packagewagl:run
    - eo3-to-stac = eodatasets3.scripts.tostac:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<3.12
    - pip
  run:
    - python >=3.9,<3.12
    - affine
    - attrs >=18.1
    - boltons
    - botocore
    - boto3
    - cattrs
    - ciso8601
    - click
    - defusedxml
    - fiona
    - h5py
    - jsonschema >=3
    - numpy >=1.15.4
    - pyproj
    - rasterio
    - ruamel.yaml
    - scipy
    - shapely
    - structlog
    - xarray
    - datacube
    - python-rapidjson
    - pystac >=1.1.0

test:
  imports:
    - eodatasets3
  commands:
    - pip check
    - eo3-validate --help
    - eo3-prepare --help
    - eo3-recompress-tar --help
    - eo3-package-wagl --help
    - eo3-to-stac --help
  requires:
    - pip

about:
  home: https://github.com/opendatacube/eo-datasets
  summary: Packaging, metadata and provenance for OpenDataCube EO3 datasets
  dev_url: https://github.com/opendatacube/eo-datasets
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Ariana-B
    - omad
    - SpacemanPaul
