{% set name = "eodatasets3" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5f5110cb95c09ed58bd1107428b7640160aa6683a4e5a41cc8156371839ab159

build:
  entry_points:
    - eo3-validate = eodatasets3.validate:run
    - eo3-prepare = eodatasets3.scripts.prepare:run
    - eo3-recompress-tar = eodatasets3.scripts.recompress:main
    - eo3-package-wagl = eodatasets3.scripts.packagewagl:run
    - eo3-to-stac = eodatasets3.scripts.tostac:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - affine
    - attrs >=18.1
    - boltons
    - botocore
    - boto3
    - cattrs
    - ciso8601
    - click
    - defusedxml
    - fiona
    - h5py
    - jsonschema >=3
    - numpy >=1.15.4,<2
    - pyproj
    - rasterio
    - ruamel.yaml
    - scipy
    - shapely
    - structlog
    - xarray
    - datacube >=1.9.0
    - python-rapidjson
    - pystac >=1.1.0

test:
  imports:
    - eodatasets3
  commands:
    - pip check
    - eo3-validate --help
    - eo3-prepare --help
    - eo3-recompress-tar --help
    - eo3-package-wagl --help
    - eo3-to-stac --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opendatacube/eo-datasets
  summary: Packaging, metadata and provenance for OpenDataCube EO3 datasets
  dev_url: https://github.com/opendatacube/eo-datasets
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Ariana-B
    - omad
    - SpacemanPaul
